const initialFilms = [
  {
    fkod: 1,
    filmcim: 'Ágnes öcsénk',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'német',
    mufaj: 'dráma',
    hossz: 115,
  },
  {
    fkod: 2,
    filmcim: 'Az állomásfőnök',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'dráma',
    hossz: 88,
  },
  {
    fkod: 3,
    filmcim: 'Álmodozók',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'angol-francia-olasz',
    mufaj: 'dráma',
    hossz: 110,
  },
  {
    fkod: 4,
    filmcim: 'Amelie csodálatos élete',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'francia-német',
    mufaj: 'vígjáték',
    hossz: 117,
  },
  {
    fkod: 5,
    filmcim: 'Annie Hall',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'vígjáték',
    hossz: 89,
  },
  {
    fkod: 6,
    filmcim: 'Anyám a lányokat szereti',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'spanyol',
    mufaj: 'vígjáték',
    hossz: 96,
  },
  {
    fkod: 7,
    filmcim: 'Anyátlanok',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'japán',
    mufaj: 'játékfilm',
    hossz: 141,
  },
  {
    fkod: 8,
    filmcim: 'Apokalipszis most - rendezői változat',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'dráma',
    hossz: 202,
  },
  {
    fkod: 9,
    filmcim: 'Apokalipszis most I-II;',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'dráma',
    hossz: 159,
  },
  {
    fkod: 10,
    filmcim: 'Arizonai álmodozók',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'dráma',
    hossz: 135,
  },
  {
    fkod: 11,
    filmcim: 'Bábok',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'japán',
    mufaj: 'dráma',
    hossz: 109,
  },
  {
    fkod: 12,
    filmcim: 'Beszélj hozzá!',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'spanyol',
    mufaj: 'dráma',
    hossz: 109,
  },
  {
    fkod: 13,
    filmcim: 'Bin-jip - Lopakodó lelkek',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'dél-koreai-japán',
    mufaj: 'dráma',
    hossz: 88,
  },
  {
    fkod: 14,
    filmcim: 'A bíró és a hóhér',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'NSZK-olasz',
    mufaj: 'krimi',
    hossz: 90,
  },
  {
    fkod: 15,
    filmcim: 'Broken Flowers - Hervadó virágok',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai-francia',
    mufaj: 'vígjáték',
    hossz: 105,
  },
  {
    fkod: 16,
    filmcim: 'A bűvös körhinta',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'francia',
    mufaj: 'animációs',
    hossz: 85,
  },
  {
    fkod: 17,
    filmcim: 'Cápasrác és Lávalány kalandjai',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'kalandfilm',
    hossz: 112,
  },
  {
    fkod: 18,
    filmcim: 'Charlie és a csokigyár',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai-angol',
    mufaj: 'vígjáték',
    hossz: 106,
  },
  {
    fkod: 19,
    filmcim: 'Che Guevara: A motoros naplója',
    szines: 0,
    szinkron: 'fel',
    szarmazas: 'amerikai-angol-argentin-német',
    mufaj: 'dráma',
    hossz: 128,
  },
  {
    fkod: 20,
    filmcim: 'Csak szex és más semmi',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'vígjáték',
    hossz: 93,
  },
  {
    fkod: 21,
    filmcim: 'Csodacsibe',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'animációs',
    hossz: 77,
  },
  {
    fkod: 22,
    filmcim: 'Csodálatos Júlia',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'kanadai',
    mufaj: '',
    hossz: 104,
  },
  {
    fkod: 23,
    filmcim: 'Datolya',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'belga-francia-tunéziai',
    mufaj: '',
    hossz: 82,
  },
  {
    fkod: 24,
    filmcim: 'Dig! - Ezt kapd ki!',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'dokumentum',
    hossz: 107,
  },
  {
    fkod: 25,
    filmcim: 'A diktátor',
    szines: 0,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'filmszatíra',
    hossz: 120,
  },
  {
    fkod: 26,
    filmcim: 'Dogville - A menedék',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'dán-svéd-norvég-német-finn-olasz-japán-angol-amerikai',
    mufaj: 'dráma',
    hossz: 177,
  },
  {
    fkod: 27,
    filmcim: 'Domino',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'francia-amerikai',
    mufaj: 'akció',
    hossz: 127,
  },
  {
    fkod: 28,
    filmcim: 'Durr; durr és csók',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'thriller',
    hossz: 103,
  },
  {
    fkod: 29,
    filmcim: 'Edukators',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'német-osztrák',
    mufaj: 'játékfilm',
    hossz: 127,
  },
  {
    fkod: 30,
    filmcim: 'Egy cipőben',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'vígjáték',
    hossz: 130,
  },
  {
    fkod: 31,
    filmcim: 'Egy hulla, egy falafel és a többiek…',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'ausztrál-olasz',
    mufaj: 'vígjáték',
    hossz: 107,
  },
  {
    fkod: 32,
    filmcim: 'Egy szoknya, egy nadrág',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'vígjáték',
    hossz: 95,
  },
  {
    fkod: 33,
    filmcim: 'Elveszett jelentés',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai-japán',
    mufaj: 'dráma',
    hossz: 102,
  },
  {
    fkod: 34,
    filmcim: 'Én, Pán Péter',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'angol-amerikai',
    mufaj: 'dráma',
    hossz: 106,
  },
  {
    fkod: 35,
    filmcim: 'Eros',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai-olasz-hongkongi-kínai-francia-luxemburgi-angol',
    mufaj: 'dráma',
    hossz: 104,
  },
  {
    fkod: 36,
    filmcim: 'Fej vagy írás',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'vígjáték',
    hossz: 90,
  },
  {
    fkod: 37,
    filmcim: 'Fekete Kefe',
    szines: 0,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'vígjáték',
    hossz: 80,
  },
  {
    fkod: 38,
    filmcim: 'A fény ösvényei',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'dráma',
    hossz: 89,
  },
  {
    fkod: 39,
    filmcim: 'Futball faktor',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'angol',
    mufaj: 'dráma',
    hossz: 91,
  },
  {
    fkod: 40,
    filmcim: 'Fűrész 2',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'thriller',
    hossz: 93,
  },
  {
    fkod: 41,
    filmcim: 'Galaxis útikalauz stopposoknak',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai-angol',
    mufaj: 'vígjáték',
    hossz: 110,
  },
  {
    fkod: 42,
    filmcim: 'Garfield',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'vígjáték',
    hossz: 81,
  },
  {
    fkod: 43,
    filmcim: 'Genezis',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'francia-olasz',
    mufaj: 'természetfilm',
    hossz: 81,
  },
  {
    fkod: 44,
    filmcim: 'Getno',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'játékfilm',
    hossz: 95,
  },
  {
    fkod: 45,
    filmcim: 'Grimm',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'cseh-amerikai',
    mufaj: 'fantasy',
    hossz: 118,
  },
  {
    fkod: 46,
    filmcim: 'Ha igaz volna…',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'vígjáték',
    hossz: 95,
  },
  {
    fkod: 47,
    filmcim: 'A halott menyasszony',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'angol',
    mufaj: 'animációs',
    hossz: 78,
  },
  {
    fkod: 48,
    filmcim: 'Harry Potter és a Tűz Serlege',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'fantasy',
    hossz: 157,
  },
  {
    fkod: 49,
    filmcim: 'Hawaii, Oslo',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'dán-svéd-norvég',
    mufaj: 'dráma',
    hossz: 125,
  },
  {
    fkod: 50,
    filmcim: 'A hetedik nap',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'spanyol',
    mufaj: 'dráma',
    hossz: 103,
  },
  {
    fkod: 51,
    filmcim: 'Hétköznapi mennyország',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'svéd',
    mufaj: 'dráma',
    hossz: 130,
  },
  {
    fkod: 52,
    filmcim: 'Híd a Kwai folyón',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'angol-amerikai',
    mufaj: 'dráma',
    hossz: 161,
  },
  {
    fkod: 53,
    filmcim: 'Hideg csontok',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'spanyol',
    mufaj: 'thriller',
    hossz: 100,
  },
  {
    fkod: 54,
    filmcim: 'Holdfényév',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'dráma',
    hossz: 117,
  },
  {
    fkod: 55,
    filmcim: 'Hölgyek levendulában',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'angol',
    mufaj: 'dráma',
    hossz: 103,
  },
  {
    fkod: 56,
    filmcim: 'Hős',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'hongkongi',
    mufaj: '',
    hossz: 96,
  },
  {
    fkod: 57,
    filmcim: 'A hősök nem pihennek',
    szines: -1,
    szinkron: '',
    szarmazas: 'francia-osztrák',
    mufaj: 'dráma',
    hossz: 104,
  },
  {
    fkod: 58,
    filmcim: 'Human Traffic',
    szines: -1,
    szinkron: '',
    szarmazas: 'angol-ír',
    mufaj: 'vígjáték',
    hossz: 99,
  },
  {
    fkod: 59,
    filmcim: 'Hurrá, nyaralunk!',
    szines: 0,
    szinkron: 'mb',
    szarmazas: 'szovjet',
    mufaj: 'ifjúsági',
    hossz: 74,
  },
  {
    fkod: 60,
    filmcim: 'Az igazi Mikulás',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'játékfilm',
    hossz: 90,
  },
  {
    fkod: 61,
    filmcim: 'Az igazság fogságában',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'kanadai',
    mufaj: '',
    hossz: 108,
  },
  {
    fkod: 62,
    filmcim: 'Az ígéret - Fényes nappal történt',
    szines: 0,
    szinkron: 'fel',
    szarmazas: 'NSZK-svájci-spanyol',
    mufaj: 'krimi',
    hossz: 90,
  },
  {
    fkod: 63,
    filmcim: 'Az ígéret megszállottja',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'dráma',
    hossz: 124,
  },
  {
    fkod: 64,
    filmcim: 'Intimitás',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'francia-angol-német-spanyol',
    mufaj: 'dráma',
    hossz: 115,
  },
  {
    fkod: 65,
    filmcim: 'Isten városa',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'brazil-francia',
    mufaj: 'dráma',
    hossz: 130,
  },
  {
    fkod: 66,
    filmcim: 'Játszik még a szív',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'angol',
    mufaj: 'vígjáték',
    hossz: 100,
  },
  {
    fkod: 67,
    filmcim: 'Johanna',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'operafilm',
    hossz: 90,
  },
  {
    fkod: 68,
    filmcim: 'Kairó bíbor rózsája',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'vígjáték',
    hossz: 84,
  },
  {
    fkod: 69,
    filmcim: 'Kávé és cigaretta',
    szines: 0,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'zenés',
    hossz: 95,
  },
  {
    fkod: 70,
    filmcim: 'Kész cirkusz',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'vígjáték',
    hossz: 74,
  },
  {
    fkod: 71,
    filmcim: 'A kilencedik nap',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'német-luxemburgi',
    mufaj: 'dráma',
    hossz: 98,
  },
  {
    fkod: 72,
    filmcim: 'King Kong',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'új-zélandi',
    mufaj: '',
    hossz: 188,
  },
  {
    fkod: 73,
    filmcim: 'Kontroll',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'thriller',
    hossz: 102,
  },
  {
    fkod: 74,
    filmcim: 'Kőkemény család',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'vígjáték',
    hossz: 104,
  },
  {
    fkod: 75,
    filmcim: 'A közvetítő',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'dokumentum',
    hossz: 89,
  },
  {
    fkod: 76,
    filmcim: 'Kulcsár & Haverok',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: '',
    hossz: 80,
  },
  {
    fkod: 77,
    filmcim: 'Kutyaszorítóban',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'thriller',
    hossz: 99,
  },
  {
    fkod: 78,
    filmcim: 'Kutyátlanok kíméljenek',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'vígjáték',
    hossz: 98,
  },
  {
    fkod: 79,
    filmcim: 'Lakótársat keresünk',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'francia-spanyol',
    mufaj: 'vígjáték',
    hossz: 120,
  },
  {
    fkod: 80,
    filmcim: 'Leány gyöngy fülbevalóval',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'angol-luxemburgi',
    mufaj: 'dráma',
    hossz: 95,
  },
  {
    fkod: 81,
    filmcim: 'Légcsavar',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'thriller',
    hossz: 98,
  },
  {
    fkod: 82,
    filmcim: 'A legtöbb ember Kínában él…',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'norvég',
    mufaj: 'dráma',
    hossz: 82,
  },
  {
    fkod: 83,
    filmcim: 'Lélektől lélekig',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'francia-dél-afrikai-angol',
    mufaj: 'kalandfilm',
    hossz: 122,
  },
  {
    fkod: 84,
    filmcim: 'Madagaszkár',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'animációs',
    hossz: 80,
  },
  {
    fkod: 85,
    filmcim: 'Magyar vándor',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'vígjáték',
    hossz: 110,
  },
  {
    fkod: 86,
    filmcim: 'Manderlay',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'dán-svéd-francia-német-amerikai',
    mufaj: 'dráma',
    hossz: 139,
  },
  {
    fkod: 87,
    filmcim: 'Manhattan',
    szines: 0,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'vígjáték',
    hossz: 96,
  },
  {
    fkod: 88,
    filmcim: 'Maszájok',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'francia',
    mufaj: 'dráma',
    hossz: 94,
  },
  {
    fkod: 89,
    filmcim: 'Még mindig lakótársat keresünk',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'francia-angol',
    mufaj: 'vígjáték',
    hossz: 125,
  },
  {
    fkod: 90,
    filmcim: 'Melinda és Melinda',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'vígjáték',
    hossz: 100,
  },
  {
    fkod: 91,
    filmcim: 'Mennyország most',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'francia-német-holland-izrael',
    mufaj: '',
    hossz: 90,
  },
  {
    fkod: 92,
    filmcim: 'Mezítlábas szerelem',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'német',
    mufaj: 'vígjáték',
    hossz: 110,
  },
  {
    fkod: 93,
    filmcim: 'Mi a csudát tudunk a világról?',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'játékfilm',
    hossz: 108,
  },
  {
    fkod: 94,
    filmcim: 'Mint egy angyal',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'francia-olasz',
    mufaj: 'dráma',
    hossz: 110,
  },
  {
    fkod: 95,
    filmcim: 'Monsieur Ibrahim és a Korán virágai',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'francia-török',
    mufaj: 'dráma',
    hossz: 94,
  },
  {
    fkod: 96,
    filmcim: 'Naqoyqatsi - Erőszakos világ',
    szines: -1,
    szinkron: 'szöv nélkül',
    szarmazas: 'amerikai',
    mufaj: 'filmesszé',
    hossz: 89,
  },
  {
    fkod: 97,
    filmcim: 'Narnia Krónikái - Az oroszlán, a boszorkány és a ruhásszekrény',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai-új-zélandi',
    mufaj: 'fantasy',
    hossz: 140,
  },
  {
    fkod: 98,
    filmcim: 'Nesze neked, Pete Tong!',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'angol-kanadai',
    mufaj: 'vígjáték',
    hossz: 90,
  },
  {
    fkod: 99,
    filmcim: 'Nézz balra, ott egy svéd!',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'dán',
    mufaj: 'vígjáték',
    hossz: 90,
  },
  {
    fkod: 100,
    filmcim: 'Nyomorultak',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'francia-olasz-NDK',
    mufaj: 'dráma',
    hossz: 225,
  },
  {
    fkod: 101,
    filmcim: 'Oldboy',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'dél-koreai',
    mufaj: 'thriller',
    hossz: 120,
  },
  {
    fkod: 102,
    filmcim: 'Az operaház fantomja',
    szines: -1,
    szinkron: '',
    szarmazas: 'amerikai',
    mufaj: 'musical',
    hossz: 92,
  },
  {
    fkod: 103,
    filmcim: 'Ördögűzés Emily Rose üdvéért',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'horror',
    hossz: 119,
  },
  {
    fkod: 104,
    filmcim: 'Pata-csata',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'dél-afrikai-amerikai',
    mufaj: 'vígjáték',
    hossz: 94,
  },
  {
    fkod: 105,
    filmcim: 'Pingvinek vándorlása',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'francia',
    mufaj: 'dokumentum',
    hossz: 85,
  },
  {
    fkod: 106,
    filmcim: 'A pityergő teve története',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'német-mongol',
    mufaj: 'dokumentum',
    hossz: 87,
  },
  {
    fkod: 107,
    filmcim: 'Ponyvaregény - Pulp Fiction',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'filmszatíra',
    hossz: 150,
  },
  {
    fkod: 108,
    filmcim: 'Porcelánbaba',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'dráma',
    hossz: 74,
  },
  {
    fkod: 109,
    filmcim: 'Rap, Revü, Rómeó',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'vígjáték',
    hossz: 82,
  },
  {
    fkod: 110,
    filmcim: 'A Rashevski tangó',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'belga-luxemburgi-francia',
    mufaj: '',
    hossz: 90,
  },
  {
    fkod: 111,
    filmcim: 'Rekonstrukció',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'dán',
    mufaj: 'dráma',
    hossz: 88,
  },
  {
    fkod: 112,
    filmcim: 'A repülő tőrök klánja',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'kínai-hongkongi',
    mufaj: 'akció',
    hossz: 111,
  },
  {
    fkod: 113,
    filmcim: 'A rövidek éjszakája',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'francia-angol-spanyol-dán',
    mufaj: 'rövidfilm',
    hossz: 68,
  },
  {
    fkod: 114,
    filmcim: 'Segítség, hal lettem!',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'dán-ír-német',
    mufaj: 'animációs',
    hossz: 80,
  },
  {
    fkod: 115,
    filmcim: 'Senki nem tud semmit',
    szines: 0,
    szinkron: 'mb',
    szarmazas: 'csehszlovák',
    mufaj: 'vígjáték',
    hossz: 70,
  },
  {
    fkod: 116,
    filmcim: 'Sin City',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'akció',
    hossz: 124,
  },
  {
    fkod: 117,
    filmcim: 'Sóhajtenger - Kuba',
    szines: 0,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'rövidfilm',
    hossz: 5,
  },
  {
    fkod: 118,
    filmcim: 'Egy sorozatgyilkos nyara',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'dráma',
    hossz: 136,
  },
  {
    fkod: 119,
    filmcim: 'A sötétség útja - Mulholland Drive',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai-francia',
    mufaj: 'dráma',
    hossz: 141,
  },
  {
    fkod: 120,
    filmcim: 'Stalker',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'szovjet-NSZK',
    mufaj: 'sci-fi',
    hossz: 160,
  },
  {
    fkod: 121,
    filmcim: 'Super Size Me',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'dokumentum',
    hossz: 96,
  },
  {
    fkod: 122,
    filmcim: 'Szamszára',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'indiai-német-francia-olasz',
    mufaj: 'dráma',
    hossz: 140,
  },
  {
    fkod: 123,
    filmcim: 'Szent Lajos király hídja',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'spanyol',
    mufaj: '',
    hossz: 120,
  },
  {
    fkod: 124,
    filmcim: 'A szenvedélyek labirintusa',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'spanyol',
    mufaj: 'játékfilm',
    hossz: 100,
  },
  {
    fkod: 125,
    filmcim: 'Szerelmem nyara',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'angol',
    mufaj: 'dráma',
    hossz: 86,
  },
  {
    fkod: 126,
    filmcim: 'Szeress, ha mersz',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'francia-belga',
    mufaj: '',
    hossz: 93,
  },
  {
    fkod: 127,
    filmcim: 'Szex, szerelem, olaszok',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'olasz-svájci-angol',
    mufaj: 'vígjáték',
    hossz: 125,
  },
  {
    fkod: 128,
    filmcim: 'Szőke Kóla',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'vígjáték',
    hossz: 96,
  },
  {
    fkod: 129,
    filmcim: 'Szürke, Mercivel',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'jugoszláv-német-szlovén-szerb',
    mufaj: 'vígjáték',
    hossz: 95,
  },
  {
    fkod: 130,
    filmcim: 'Szürkület',
    szines: 0,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'krimi',
    hossz: 105,
  },
  {
    fkod: 131,
    filmcim: 'Táncos a sötétben',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'dán-svéd-francia',
    mufaj: 'dráma',
    hossz: 134,
  },
  {
    fkod: 132,
    filmcim: 'Tangó és tulipán',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'olasz-svájci',
    mufaj: 'vígjáték',
    hossz: 112,
  },
  {
    fkod: 133,
    filmcim: 'Tapló télapó',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai-német',
    mufaj: 'vígjáték',
    hossz: 98,
  },
  {
    fkod: 134,
    filmcim: 'Tavasz, Nyár, Ősz, Tél és Tavasz',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'dél-koreai-német',
    mufaj: 'dráma',
    hossz: 99,
  },
  {
    fkod: 135,
    filmcim: 'Tavasz van',
    szines: 0,
    szinkron: 'fel',
    szarmazas: 'olasz',
    mufaj: 'dráma',
    hossz: 90,
  },
  {
    fkod: 136,
    filmcim: 'Twist Olivér',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'angol-cseh-francia-olasz',
    mufaj: 'dráma',
    hossz: 130,
  },
  {
    fkod: 137,
    filmcim: 'Utazások egy szerzetessel',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'dokumentum',
    hossz: 65,
  },
  {
    fkod: 138,
    filmcim: 'Ütközések',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'amerikai-német',
    mufaj: 'dráma',
    hossz: 113,
  },
  {
    fkod: 139,
    filmcim: 'Üvegfal',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'játékfilm',
    hossz: 87,
  },
  {
    fkod: 140,
    filmcim: 'Üvegtigris',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'vígjáték',
    hossz: 100,
  },
  {
    fkod: 141,
    filmcim: 'Vad galamb',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'angol',
    mufaj: 'animációs',
    hossz: 76,
  },
  {
    fkod: 142,
    filmcim: 'A vágy törvénye',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'spanyol',
    mufaj: 'dráma',
    hossz: 102,
  },
  {
    fkod: 143,
    filmcim: 'Van élet a halál előtt?',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'dokumentum',
    hossz: 110,
  },
  {
    fkod: 144,
    filmcim: 'A vándorló palota',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'japán',
    mufaj: 'animációs',
    hossz: 119,
  },
  {
    fkod: 145,
    filmcim: 'Vera Drake',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'angol-francia-új-zélandi',
    mufaj: 'dráma',
    hossz: 124,
  },
  {
    fkod: 146,
    filmcim: 'Világok arca: Baraka',
    szines: -1,
    szinkron: 'szöveg nélküli',
    szarmazas: 'amerikai',
    mufaj: 'dokumentum',
    hossz: 96,
  },
  {
    fkod: 147,
    filmcim: 'Vincent, François, Paul és a többiek',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'francia-olasz',
    mufaj: 'dráma',
    hossz: 120,
  },
  {
    fkod: 148,
    filmcim: 'Vízcseppek a forró kövön',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'francia',
    mufaj: 'dráma',
    hossz: 90,
  },
  {
    fkod: 149,
    filmcim: 'Vuk',
    szines: -1,
    szinkron: '',
    szarmazas: 'magyar',
    mufaj: 'rajzfilm',
    hossz: 74,
  },
  {
    fkod: 150,
    filmcim: 'Wallace & Gromit és az Elvetemült Veteménylény',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'angol',
    mufaj: 'animációs',
    hossz: 94,
  },
  {
    fkod: 151,
    filmcim: 'Waterloo Bridge',
    szines: 0,
    szinkron: 'fel',
    szarmazas: 'amerikai',
    mufaj: 'dráma',
    hossz: 103,
  },
  {
    fkod: 152,
    filmcim: 'Whisky',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'uruguayi-argentin-német-spanyol',
    mufaj: 'komédia',
    hossz: 99,
  },
  {
    fkod: 153,
    filmcim: 'Zorro legendája',
    szines: -1,
    szinkron: 'mb',
    szarmazas: 'amerikai',
    mufaj: 'kalandfilm',
    hossz: 131,
  },
  {
    fkod: 154,
    filmcim: '5x2',
    szines: -1,
    szinkron: 'fel',
    szarmazas: 'francia',
    mufaj: 'dráma',
    hossz: 90,
  },
];
